#!/bin/bash

# m4_ignore(
echo "This is just a script template, not the script (yet) - pass it to 'argbash' to fix this." >&2
exit 11  #)Created by argbash-init v2.8.1
# ARG_POSITIONAL_SINGLE([project_name])
# ARG_DEFAULTS_POS
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO

# [ <-- needed because of Argbash

# "Bash strict mode"
set -euo pipefail
IFS=$'\n\t'

readonly SANDBOX_DIR=".sandbox"
readonly PROJECT_NAME="$_arg_project_name"

# DEV: Setup sandbox
if [[ -d "$SANDBOX_DIR" ]]; then
    echo "Resetting sandbox"
    rm -r "$SANDBOX_DIR"
fi
echo "Creating sandbox"
mkdir "$SANDBOX_DIR"
cd "$SANDBOX_DIR"


# 0: Initialize git repo
echo "Initializing git repository"
git init


# 1: Create readme
echo "Creating README.md"
echo "# $PROJECT_NAME" > README.md


# 2: Get latest .gitignore
echo "Downloading latest .gitignore for Visual Studio"
wget -O .gitignore https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore


# n: Make initial commit
echo "Initial commit"
git config user.email "invalid-email"
git config user.name "autorepo"
git add .
git commit -m "Initial commit"


# ] <-- needed because of Argbash
